remote_theme: dieghernan/chulapa
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
name: Nodal-Tools
title: Nodal-Tools
tite_separator: ""
url: "https://nodal-tools.fi"
baseurl: ""
googlefonts:
  - url: "https://fonts.googleapis.com/css2?family=Varela+Round&family=Inter:wght@400;500;600;700&display=swap"
stylesheets:
  - /assets/css/custom.css

# Chulapa navbar configuration
navbar:
  style: dual
  brand:
    img: /assets/img/logo-without-subtext.svg
  nav:
  - title: Home
    url: /
  - title: Expertise
    url: /expertise/
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contact/

footer:
copyright: "Â© 2025 Nodal-Tools"
links:
  - label: "Email"
    icon: "far fa-envelope"
    url: "mailto:first.last@nodal-tools.fi"